### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by davidlaprade** [davidlaprade/umbgov_rails#14]
TODO
--------------------------------------
The following are changes that absolutely have to be made before the initial release:
- [x] budget requests are finished #6 
    - [x] budget request emails #18 
    - [x] budget request queries #19 
- [x] recaptchas #15 
- [x] put everything in a private repo to hide secret keys
    - [x] better: put the private keys in environment variables #17 
- [x] database tables for feedback and volunteering #13 
- [x] devise password reset must work
- [ ] hosting of email addresses #11 
- [x] get Sendgrid account #16 
- [x] set up AWS S3 bucket #20 
- [x] create staging site
- [ ] create production site
- [ ] add photo cropping #32 ; WAY easier to have all that in place now than to have to fix it after people have started to upload

**Comment by davidlaprade** [comment]
Closing this out. No need to have a separate issue when the milestone is doing the same work.
