### ISSUE TITLE
Refactor budget request filter functionality

### ISSUE THREAD

**Issue by davidlaprade** [davidlaprade/umbgov_rails#88]
One of my favorite pieces of technical debt is the [filter functionality](https://github.com/davidlaprade/umbgov_rails/blob/9adacadae4d1214ffbbb31c32d1201a66d092737/app/controllers/budget_requests_controller.rb#L115-L143) on budget requests:

```ruby
  def filter
    @filter_object = BudgetRequest.new({screened: nil, status: nil}.merge filter_params)
    scope = {}
    if filter_params.present?
      [:status, :kind, :organization].each do |field|
        if filter_params[field].present?
          scope[field] = filter_params[field]
        end
      end

      if current_user && current_user.can_screen_requests
        # NOTE: the if condition directly below cannot be added into the above condition, else users with
        # screening permissions will only be shown screened requests when they do not make a selection
        if filter_params[:screened].present?
          scope[:screened] = filter_params[:screened].to_bool
        end
      else
        scope[:screened] = true
      end
    end

    @requests = BudgetRequest.where(scope).order(id: :desc)
      .paginate(page: params[:page], per_page: 20)
    @organizations = get_orgs
    @years = get_years
    render :index
  end
```

### TODO
- [ ] write an integration test for the filter functionality, make it pass with the current implementation
- [ ] create an `/app/forms` directory to house [form objects](http://railscasts.com/episodes/416-form-objects)
- [ ] create a `budget_request_filter_form.rb` file in the new forms directory and define a form object, `BudgetRequestFilterForm` there
  - the object should be initialized with the `filter_params` defined [here](https://github.com/davidlaprade/umbgov_rails/blob/9adacadae4d1214ffbbb31c32d1201a66d092737/app/controllers/budget_requests_controller.rb#L255-L257)
  - it should be possible to initialize the object with no params
  - the object should expose a public `#filter` method, which returns a bunch of BudgetRequests based on the filter params passed in; basically, this is where you're going to extract the logic that's in the controller [action](https://github.com/davidlaprade/umbgov_rails/blob/9adacadae4d1214ffbbb31c32d1201a66d092737/app/controllers/budget_requests_controller.rb#L115-L143) into this method
  ```ruby
    filter_form = BudgetRequestFilterForm.new(filter_params)
    budget_requests = filter_form.filter
  ```
- [ ] instantiate the `BudgetRequestFilterForm` in the index [here](https://github.com/davidlaprade/umbgov_rails/blob/9adacadae4d1214ffbbb31c32d1201a66d092737/app/controllers/budget_requests_controller.rb#L56)
- [ ] remove the `get_years` method and the `@years` variables being set in this controller: they aren't actually used anywhere
- [ ] remove the `get_organizations` method from the controller and put it into the form object, also get rid of the `@organizations` instance var
- [ ] the new controller action should look something like this:

    ```ruby
    def filter
      @filter_object = BudgetRequestFilterForm.new(filter_params)
      @requests = @filter_object.filter
        .paginate(page: params[:page], per_page: 20)
      render :index
    end
    ```
- [ ] refactor the actual HTML [form](https://github.com/davidlaprade/umbgov_rails/blob/9adacadae4d1214ffbbb31c32d1201a66d092737/app/views/budget_requests/_search_bar.html.erb) to use the form object just created
- [ ] write unit tests for the form object
- [ ] move the `BudgetRequestsController#filter` action into a new controller and action: `FilterController#budget_requests`
  - replace associated routes throughout the code
- [ ] __BONUS POINTS__ make filtering AJAXy, so that the browser doesn't have to reload each time someone enters a new series of filters, or clears the filters

**Comment by anthonyadrian** [comment]
Some questions about development:

1. There are no budget requests for me to view. How do I populate them? I did rake db:seed to no avail. 
2. When I submit a budget request, I cannot view it afterward. The app says that only reviewed requests will be viewable. How might I go about doing that on my end??
3. As for testing, I see that right now you are testing the spec not by whether certain lines of info are visible after a budget request but instead you are checking the properties of the last budget request that was created. Do I just check whether the page returns the right results on a filtered request? As in, if the filter was for a ‘pending’ request: expect( page ).to have_content “Pending”. Does that work?
4. In the controller, why does the filter method create a new BudgetRequest? Why isn’t it just doing something like BR.find(blah blah blah)? I must be missing something obvious.
5. The recaptcha verification thing doesn’t work on localhost. This means I cannot create requests locally. I tried to get it to work but it says I have to fix this through the admin panel. You have access to such a panel? If so, do you want to give me access?

**Comment by anthonyadrian** [comment]
Update to question #4:

I see in the method you are returning 'BudgetRequest.where(scope)...' which is what I had thought you would do. However, I'm still unclear why there is initially a new BR being created as the first step of the method.

**Comment by davidlaprade** [comment]
@anthonyadrian:

> There are no budget requests for me to view. How do I populate them? 

I recommend importing the sql dump from production locally. Otherwise, it's probably easiest to create them through the rails console -- though there'll be a lot of attributes you have to set.

>  The app says that only reviewed requests will be viewable. How might I go about doing that on my end?

Create an admin account for yourself. This will allow you to view requests right after they are created, and "screen" them for public viewing on the site.

> Do I just check whether the page returns the right results on a filtered request?

Sounds good to me! I'd probably also check not only that you find `Pending` but that you also __don't__ find the other statuses, whatever they are (can't remember).

> In the controller, why does the filter method create a new BudgetRequest?

Just my crappy coding. I wrote this before I learned about form objects. I was instantiating a dummy ActiveRecord object to pass into the form so that it would auto-populate certain fields and validate others. Total hack.

> The recaptcha verification thing doesn’t work on localhost. 

Hmm. That's weird. What's not working? If I remember correctly, I set up the code in most places to ignore the recaptcha response if the app was running in the development environment. So even if the recaptcha seems broken, it'll still pass. [Example](https://github.com/davidlaprade/umbgov_rails/blob/9adacadae4d1214ffbbb31c32d1201a66d092737/app/controllers/budget_requests_controller.rb#L273).

**Comment by anthonyadrian** [comment]
Okay I imported the psql dump. Now I've got lots of data to work with. I'll work on changing my user to an admin.

As for the recaptcha problem, I think I misread something. I ran into a problem earlier and for whatever reason it seemed like recaptcha was the problem. But I've been able to create both a B&F and a Club request just fine. Guess I was wrong.

Thanks for your help.

**Comment by anthonyadrian** [comment]
Update: I made myself an admin (and the president because yolo) and I can indeed screen requests. Thank you, sir.

**Comment by davidlaprade** [comment]
👍

**Comment by anthonyadrian** [comment]
Okay so now I've written a test to check the filter functionality. I couldn't _just_ check for the presence of 'pending' and the absence of 'denied' because those radio buttons stay on the page no matter what. Instead I had to select the table that actually shows the results. But there remains a problem. 

The test database doesn't have any sample requests. That is, the test result just gives me the "No budget request currently available. Please come back again soon!" message. I seeded the test database, but that didn't work. 

Any idea what's going on?

**Comment by anthonyadrian** [comment]
Hmmm okay so I tried using the development database as the test db, and it now has data. But it seems like the actual filtering isn't happening on the test. In the test, I tell it to select 'pending' and then click the button 'filter', but the test results are being filtered. I thought maybe it was that JS problem we were having earlier, so I tested again with selenium but that didn't work either.

**Comment by davidlaprade** [comment]
> The test database doesn't have any sample requests

Right... We should probably create a budget request factory using [`FactoryGirl`](https://github.com/thoughtbot/factory_girl). Then we can instantiate and persist new objects quickly and easily during test setup. Checkout what I did for the [user factory](https://github.com/davidlaprade/umbgov_rails/blob/master/spec/factories/users.rb).

> it seems like the actual filtering isn't happening on the test

As I think about this more, an integration test probably isn't the best fit for this. They're just SO finicky. Let's start with some controller tests. And what you can do is `expect( assigns(:requests) ).to include ....` and make sure the filtering is happening the way you expect. [Here's](https://github.com/davidlaprade/umbgov_rails/blob/master/spec/controllers/user_controller_spec.rb) an example of a controller spec that tests the instance variable assignments based on the parameters passed into the action.
